# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Junteng Liu
email: jliugi@connect.ust.hk
description: >- # this means to ignore newlines until "baseurl:"
  Junteng Liu is a first-year PhD candidate at HKUST NLP Group.
  His research focuses on natural language processing and machine learning,
  particularly LLM Reasoning, Reinforcement Learning, Hallucination in Vision-Language
  Models, and LLM Truthfulness and Interpretability.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davadosv-bot.github.io" # the base hostname & protocol for your site
author:
  name: Junteng Liu
  email: jliugi@connect.ust.hk
github_username: Vicent0205
twitter_username: junteng88716710
gscholar_id: tbK9jl4AAAAJ

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: publication
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: portfolio
  - scope:
      path: ""
      type: "talks"
    values:
      layout: talk
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: teaching
